import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import ThemeProvider from "@/Theme/ThemeProvider";
import ThemeSwitcher from "@/Theme/ThemeSwitcher";

const robotoSans = Roboto({
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={robotoSans.className}>
        <ThemeProvider>
          <Header className="container" />
          <main className="container">
            {children}
            <ThemeSwitcher />
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
